//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFFlowerShop.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.SaleProduct = new HashSet<SaleProduct>();
        }
    
        public int ID_Product { get; set; }
        public string Name { get; set; }
        public int ID_Color { get; set; }
        public int Price { get; set; }
        public int ID_Vid { get; set; }
        public int ID_Suppliers { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual Colors Colors { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        public virtual Vid Vid { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleProduct> SaleProduct { get; set; }
    }
}
